name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count Lines of Code
      id: lines-of-code
      uses: davidahouse/loc@v1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Output Lines of Code
      run: echo ${{ steps['lines-of-code'].outputs.lines }}
