name: Count Lines of Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install cloc
      run: npm install -g cloc

    - name: Count Lines of Code
      run: cloc --vcs=git
